### ISSUE TITLE
안녕하세요 설치 중에 에러가 나서 이슈 올립니다.

### ISSUE THREAD

**Issue by seongjoojin** [ifsnow/react-native-networking-patch#1]
yarn으로 설치 도중 아래와 같이 오류가 납니다.

```
error /프로젝트명/node_modules/react-native-networking-patch: Command failed.
Exit code: 1
Command: yarn run patch
Arguments: 
Directory: /프로젝트명/node_modules/react-native-networking-patch
Output:
yarn run v1.22.4
$ node patch.js
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, copyfile '/프로젝트명/node_modules/react-native-networking-patch/patches/0.62.2/library/0.62.2/react-native-0.62.2-javadoc.jar' -> '/프로젝트명/node_modules/react-native/android/com/facebook/react/react-native/0.62.2/react-native-0.62.2-javadoc.jar'
    at Object.copyFileSync (fs.js:1876:3)
    at /프로젝트명/node_modules/react-native-networking-patch/patch.js:91:6
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/프로젝트명/node_modules/react-native-networking-patch/patch.js:89:31)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/프로젝트명/node_modules/react-native-networking-patch/patches/0.62.2/library/0.62.2/react-native-0.62.2-javadoc.jar',
  dest: '/프로젝트명/node_modules/react-native/android/com/facebook/react/react-native/0.62.2/react-native-0.62.2-javadoc.jar'
```

현재 사용 중인 RN버전은 0.62.0입니다.
감사합니다.

**Comment by ifsnow** [comment]
각 버전의 최신 버전만 대응하고 있는데요. 이 부분 체크를 더 강화해야겠네요.
React Naitve 0.62.2 로 버전업 하시고 한 번 해봐주세요.
0.62.0에서 0.62.2는 아무 문제없이 업그레이드 됐던 것 같네요.

**Comment by seongjoojin** [comment]
답변 감사합니다.
진행해보고 피드백드리겠습니다.

**Comment by seongjoojin** [comment]
0.62.2 버전에서 이상없이 설치되는 것을 확인하였습니다:)
감사합니다!

**Comment by ifsnow** [comment]
해결이 됐다니 다행이네요!
